package com.madding.shared.javacc.math.n;
/* Generated By:JavaCC: Do not edit this line. eg4Visitor.java Version 5.0 */
public interface eg4Visitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTMyOtherID node, Object data);
  public Object visit(ASTInteger node, Object data);
}
/* JavaCC - OriginalChecksum=546a0b8c1734945f22b0aac0186113e3 (do not edit this line) */
