/* Generated By:JavaCC: Do not edit this line. FLWConstants.java */

package com.aqnote.shared.javacc.misc.flw;

/**
 * Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FLWConstants {

    /** End of File. */
    int      EOF              = 0;
    /** RegularExpression Id. */
    int      FOUR_LETTER_WORD = 5;
    /** RegularExpression Id. */
    int      FIVE_LETTER_WORD = 6;
    /** RegularExpression Id. */
    int      DIGIT            = 7;
    /** RegularExpression Id. */
    int      LETTER           = 8;
    /** RegularExpression Id. */
    int      OTHER            = 9;

    /** Lexical state. */
    int      DEFAULT          = 0;

    /** Literal token values. */
    String[] tokenImage       = { "<EOF>", "\" \"", "\"\\r\"", "\"\\n\"", "\"\\r\\n\"", "<FOUR_LETTER_WORD>",
                                  "<FIVE_LETTER_WORD>", "<DIGIT>", "<LETTER>", "<OTHER>", };

}
