package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTArrayAssignmentStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAssignmentStatement extends SimpleNode {
  public ASTArrayAssignmentStatement(int id) {
    super(id);
  }

  public ASTArrayAssignmentStatement(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d73444ca4644576a389a2049c540504e (do not edit this line) */
