package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTArrayType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayType extends SimpleNode {
  public ASTArrayType(int id) {
    super(id);
  }

  public ASTArrayType(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1abb935997a0e7f0370096dc7f68632f (do not edit this line) */
