package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTArrayAllocationExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAllocationExpression extends SimpleNode {
  public ASTArrayAllocationExpression(int id) {
    super(id);
  }

  public ASTArrayAllocationExpression(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=22527fab3dc33a62c74b0fb4398f9ae0 (do not edit this line) */
