package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTBracketExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBracketExpression extends SimpleNode {
  public ASTBracketExpression(int id) {
    super(id);
  }

  public ASTBracketExpression(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d79e5a6427fe7b61f132bcfcd8ca3620 (do not edit this line) */
