package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTFormalParameterRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFormalParameterRest extends SimpleNode {
  public ASTFormalParameterRest(int id) {
    super(id);
  }

  public ASTFormalParameterRest(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=35d038e61dbccc994d036d7bf26c5575 (do not edit this line) */
