package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTGoal.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGoal extends SimpleNode {
  public ASTGoal(int id) {
    super(id);
  }

  public ASTGoal(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7b54e699894b8c691300b5032a297585 (do not edit this line) */
