package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTIntegerType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIntegerType extends SimpleNode {
  public ASTIntegerType(int id) {
    super(id);
  }

  public ASTIntegerType(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=389ef128767885946f4996f5b43a3ecc (do not edit this line) */
