package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTMinusExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMinusExpression extends SimpleNode {
  public ASTMinusExpression(int id) {
    super(id);
  }

  public ASTMinusExpression(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2d3ccb382329f7196f8916ef5f3792b5 (do not edit this line) */
