package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTMessageSend.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMessageSend extends SimpleNode {
  public ASTMessageSend(int id) {
    super(id);
  }

  public ASTMessageSend(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6b2f41eae596282b92bc157a5a654e3d (do not edit this line) */
