package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTTrueLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTrueLiteral extends SimpleNode {
  public ASTTrueLiteral(int id) {
    super(id);
  }

  public ASTTrueLiteral(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a82d3be64df14631d5f5e3aaa363ba51 (do not edit this line) */
