package com.madding.shared.javacc.minijava;
/* Generated By:JJTree: Do not edit this line. ASTThisExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTThisExpression extends SimpleNode {
  public ASTThisExpression(int id) {
    super(id);
  }

  public ASTThisExpression(MiniJavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ccbca241a892d88ac356b9b9d11d9fce (do not edit this line) */
