/*
 * Copyright (C) 2013-2016 aqnote.com<madding.lip@gmail.com>. 
 * This library is free software; you can redistribute it and/or modify it under the terms of
 * the GNU Lesser General Public License as published by the Free Software Foundation;
 */
package com.aqnote.shared.javacc.minijava;
/* Generated By:JavaCC: Do not edit this line. MiniJavaParserTreeConstants.java Version 5.0 */
public interface MiniJavaParserTreeConstants
{
  public int JJTGOAL = 0;
  public int JJTMAINCLASS = 1;
  public int JJTTYPEDECLARATION = 2;
  public int JJTCLASSDECLARATION = 3;
  public int JJTCLASSEXTENDSDECLARATION = 4;
  public int JJTVARDECLARATION = 5;
  public int JJTMETHODDECLARATION = 6;
  public int JJTFORMALPARAMETERLIST = 7;
  public int JJTFORMALPARAMETER = 8;
  public int JJTFORMALPARAMETERREST = 9;
  public int JJTTYPE = 10;
  public int JJTARRAYTYPE = 11;
  public int JJTBOOLEANTYPE = 12;
  public int JJTINTEGERTYPE = 13;
  public int JJTSTATEMENT = 14;
  public int JJTBLOCK = 15;
  public int JJTASSIGNMENTSTATEMENT = 16;
  public int JJTARRAYASSIGNMENTSTATEMENT = 17;
  public int JJTIFSTATEMENT = 18;
  public int JJTWHILESTATEMENT = 19;
  public int JJTPRINTSTATEMENT = 20;
  public int JJTEXPRESSION = 21;
  public int JJTANDEXPRESSION = 22;
  public int JJTCOMPAREEXPRESSION = 23;
  public int JJTPLUSEXPRESSION = 24;
  public int JJTMINUSEXPRESSION = 25;
  public int JJTTIMESEXPRESSION = 26;
  public int JJTARRAYLOOKUP = 27;
  public int JJTARRAYLENGTH = 28;
  public int JJTMESSAGESEND = 29;
  public int JJTEXPRESSIONLIST = 30;
  public int JJTEXPRESSIONREST = 31;
  public int JJTPRIMARYEXPRESSION = 32;
  public int JJTINTEGERLITERAL = 33;
  public int JJTTRUELITERAL = 34;
  public int JJTFALSELITERAL = 35;
  public int JJTIDENTIFIER = 36;
  public int JJTTHISEXPRESSION = 37;
  public int JJTARRAYALLOCATIONEXPRESSION = 38;
  public int JJTALLOCATIONEXPRESSION = 39;
  public int JJTNOTEXPRESSION = 40;
  public int JJTBRACKETEXPRESSION = 41;


  public String[] jjtNodeName = {
    "Goal",
    "MainClass",
    "TypeDeclaration",
    "ClassDeclaration",
    "ClassExtendsDeclaration",
    "VarDeclaration",
    "MethodDeclaration",
    "FormalParameterList",
    "FormalParameter",
    "FormalParameterRest",
    "Type",
    "ArrayType",
    "BooleanType",
    "IntegerType",
    "Statement",
    "Block",
    "AssignmentStatement",
    "ArrayAssignmentStatement",
    "IfStatement",
    "WhileStatement",
    "PrintStatement",
    "Expression",
    "AndExpression",
    "CompareExpression",
    "PlusExpression",
    "MinusExpression",
    "TimesExpression",
    "ArrayLookup",
    "ArrayLength",
    "MessageSend",
    "ExpressionList",
    "ExpressionRest",
    "PrimaryExpression",
    "IntegerLiteral",
    "TrueLiteral",
    "FalseLiteral",
    "Identifier",
    "ThisExpression",
    "ArrayAllocationExpression",
    "AllocationExpression",
    "NotExpression",
    "BracketExpression",
  };
}
/* JavaCC - OriginalChecksum=c68e821aae918d29f2a9a268fb210125 (do not edit this line) */
